### PR TITLE
refactor: upgrade SDK to v1.2.1

### LINKED ISSUE #144: upgrade SDK to v1.2.1

### PR DESCRIPTION
**Pull request by hahattan**
Fix #144 

Signed-off-by: Chris Hung <chris@iotechsys.com>

### CODE REVIEW

**Comment by hahattan** [comment]
```
13:20:36 Determining the version from the project repo (version-script).
13:20:36 cat: VERSION: No such file or directory
13:20:36 The version has been set to '-20200428+b65c2ac'
13:20:36 error: cannot validate snap "edgex-device-mqtt": invalid snap version "-20200428+b65c2ac": must start with an ASCII alphanumeric (and not '-')
``` 
It seems we're missing VERSION file in this repo ?

**Comment by cloudxxx8** [comment]
@tonyespy @anonymouse64 could you please advise how to resolve the snap build issue here?  thanks.

**Comment by cloudxxx8** [comment]
@ernestojeda the snap build check blocks the PR.  Do you know how to make it to adopt the semantic version?

**Comment by anonymouse64** [comment]
The version setup for the repo has changed since the snap packaging was written:

> 00:16:40 cat: VERSION: No such file or directory
> 00:16:40 The version has been set to '-20200428+b65c2ac'
> 00:16:40 error: cannot validate snap "edgex-device-mqtt": invalid snap version "-20200428+b65c2ac": must start with an ASCII alphanumeric (and not '-')
> 00:16:40 Failed to verify directory to pack.

so it seems the VERSION file doesn't exist, which was introduced in this PR: https://github.com/edgexfoundry/device-mqtt-go/pull/131. 

I'm not sure the right way to get the version of the project anymore, how is that expected to work in the new semantic versioning world? How would the snap build job identify which version it is on given that the VERSION file no longer exists? @ernestojeda perhaps you could comment since you changed the snap devops setup in https://github.com/edgexfoundry/device-mqtt-go/pull/142 ?

**Comment by cloudxxx8** [comment]
@ernestojeda may we remove the snap check until we can resolve the version issue?

**Comment by lranjbar** [comment]
The snaps are building correctly in the pipeline. It is okay to ignore the old snap build jobs.

**Comment by cloudxxx8** [comment]
Thanks, @lranjbar

**Comment by anonymouse64** [comment]
@lranjbar 

> The snaps are building correctly in the pipeline. It is okay to ignore the old snap build jobs.

How can this be true? the snapcraft.yaml here clearly has this:

https://github.com/edgexfoundry/device-mqtt-go/blob/4f542d150f63fd84c4c4e03c791e07fdb7c9aef4/snap/snapcraft.yaml#L5-L6

which fails to build because there is no VERSION file committed to git?

**Comment by lranjbar** [comment]
In the new pipeline part of the internals are that we create a VERSION file on demand to help out with backwards compatibility in the build processes. This VERSION file is populated with the version managed by git-semver. Initially we wanted to remove that file as much as possible but there were simply too many scripts that depended on it so we started populating and overwriting it in Jenkins.

Screenshots of the passing job: (it will be cleaned up eventually by Jenkins)
image

In a PR there is no version - so it defaults to 0.0.0 this messed up isn't committed anywhere.
image

Here is the latest job from the master branch too and the snap build is still working and was pushed to latest/edge.
https://jenkins.edgexfoundry.org/blue/organizations/jenkins/edgexfoundry%2Fdevice-mqtt-go/detail/master/6/pipeline

**Comment by anonymouse64** [comment]
Thanks for the explanation, that's cool that it works in the pipeline, but I think it's a bit broken that there's no way for either 

1) PR's to build the snap and test that a snap file was actually produced (i.e. right now snapcraft will fail because there's no VERSION file)
1) local devs to build the snap on their machine. 

I think it would be better if either the snapcraft.yaml didn't use the VERSION file and instead auto-detected something from the jenkins pipeline environment to get the version number here, or if there was a dummy VERSION file committed to the repo so that local builds and PR builds produce a successful snap file when run

Anyways this is probably better discussed in a different repo because it seems all snap repos that aren't edgex-go suffer from this problem, i.e. see device-modbus-go as well. @lranjbar what repo should this issue be filed to?

**Comment by lranjbar** [comment]
Sure we can make improvements. I would file this issue in edgex-global-pipelines because it seems to be improvements to the edgeXSnap function.

**Pull request merged**
