### PR TITLE
fix: Add AuthMode settings so have ability to enable/disable Auth MQTT connections

### PR DESCRIPTION
**Pull request by lenny-intel**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/device-mqtt-go/blob/master/.github/CONTRIBUTING.md

## What is the current behavior?
No AuthMode setting so have to put empty credentials in Secret Store in secure and non-secure modes

## What is the new behavior?
Now have AuthMode setting, so don't have to have any credentials in Secret Store if set to `none`

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## New Imports

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by cloudxxx8** [comment]
we discussed about use the single broker and plan to do it, so this PR should not separate more AuthMode fields.

**Comment by lenny-intel** [comment]
> we discussed about use the single broker and plan to do it, so this PR should not separate more AuthMode fields.

@cloudxxx8 , yes but wanted to get this completed. The follow on refactoring will reduce all the connect/auth settings to one block.

**Review by cloudxxx8 — APPROVED** [review]
LGTM
@lenny-intel the conventional commit messages need to be fixed

**Comment by lenny-intel** [comment]
> the conventional commit messages need to be fixed

@cloudxxx8 , handled with squash and merge. ;-)

**Pull request merged**
