### PR TITLE
SenML format supported in MQTT messages

### PR DESCRIPTION
**Pull request by juanmagal**
This PR is introducing the possibility of receiving MQTT messages with SenML format

Please check code since I cannot be considered a go lang expert.

I have tested with a mosquitto broker and with mainflux server and it works.

### CODE REVIEW

**Comment by SteveOss** [comment]
@juanmagal Could you update this PR to resolve conflicts and fix the check failures.

**Comment by juanmagal** [comment]
Should I also change these other PRs: https://github.com/edgexfoundry/edgex-go/pull/1059 & https://github.com/edgexfoundry/device-sdk-go/pull/164?
They were closed due to SenML support was not going to be included in Edimburgh, should I understand this feature might be included in Fuji?

**Comment by juanmagal** [comment]
@cloudxxx8 I don't have any problem on presenting anything if needed, but as I commented several months ago, I am not representing any company in EdgeX and do not have any special commercial interest on supporting SenML in EdgeX; but that time I just wanted to provide the code I created for my Master Thesis to this community since I thought somebody could benefit from it and take advantage of my work. At this moment I could have done any change if needed.
Now, with the last changes made on the interfaces between EdgeX Device Services and EdgeX Core, there will be significant changes on the code I made and I have already finished the Thesis.
If someone in the community thinks SenML support could be interesting and wants to take the lead, I can explain my ideas and offer some help, but unfortunately at this moment I cannot commit to introduce all the required changes.
Hope you understand the situation.

**Comment by cloudxxx8** [comment]
@juanmagal no problem.  thanks for your interest on EdgeX.  some people also contribute to the community personally.  I thought the source code change might not be a big issue.  The point is the design.    We have to meet the agreement of the use case and design in the community, and we could complete the remaining development work.  Could you please extract some content from your thesis to present the idea first?  Then, we could schedule some time in the working group meeting to discuss.  Thanks.

**Comment by cloudxxx8** [comment]
close this PR due to no activity

**Pull request closed without merging**
