### PR TITLE
fix: Return error instead of the panic if required config not found

### LINKED ISSUE #160: Service panic if IncomingUser is missing from configuration
Version: 1.2.1

While testing the service to determine if I could make TLS connections to a broker work, I commented out all ***User** and ***Password** config keys from `configuration.toml`as my broker wasn't configured for password authentication.

When I started the service for the first time, it crashes with the following panic output to the log:

```
21:23:19Z device-mqtt[1778]: panic: read MQTT driver configuration failed: unable to load config, 'IncomingUser' not exist
21:23:19Z device-mqtt[1778]: goroutine 1 [running]:
21:23:19Z device-mqtt[1778]: github.com/edgexfoundry/device-mqtt-go/internal/driver.(*Driver).Initialize(0xc0000a4410, 0xb188a0, 0xc0000a56d0, 0xc0001ff7a0, 0xc00002bf20, 0x0, 0x0)
21:23:19Z device-mqtt[1778]:       /build/parts/device-mqtt/src/internal/driver/driver.go:67 +0x184
21:23:19Z device-mqtt[1778]: github.com/edgexfoundry/device-sdk-go/pkg/service.(*Bootstrap).BootstrapHandler(0xc00000e0f8, 0xb15380, 0xc0000807c0, 0xc000029e60, 0xbfc48c91c51df329, 0xa5b1b, 0xeadee0, 0x6fc23ac00, 0x3b9aca00, 0xc00000c860, ...)
21:23:19Z device-mqtt[1778]:       /root/go/pkg/mod/github.com/edgexfoundry/device-sdk-go@v1.2.2/pkg/service/init.go:77 +0x43c
21:23:19Z device-mqtt[1778]: github.com/edgexfoundry/go-mod-bootstrap/bootstrap.RunAndReturnWaitGroup(0xb15380, 0xc0000807c0, 0xc00002f400, 0xb1b000, 0xc0000ec1c0, 0xa4022b, 0x11, 0xa40a83, 0x12, 0xb185a0, ...)
21:23:19Z device-mqtt[1778]:       /root/go/pkg/mod/github.com/edgexfoundry/go-mod-bootstrap@v0.0.33/bootstrap/bootstrap.go:153 +0x69f
21:23:19Z device-mqtt[1778]: github.com/edgexfoundry/go-mod-bootstrap/bootstrap.Run(0xb15380, 0xc0000807c0, 0xc00002f400, 0xb1b000, 0xc0000ec1c0, 0xa4022b, 0x11, 0xa40a83, 0x12, 0xb185a0, ...)
21:23:19Z device-mqtt[1778]:       /root/go/pkg/mod/github.com/edgexfoundry/go-mod-bootstrap@v0.0.33/bootstrap/bootstrap.go:178 +0x135
21:23:19Z device-mqtt[1778]: github.com/edgexfoundry/device-sdk-go/pkg/service.Main(0xa4022b, 0x11, 0xaf925c, 0x5, 0x9fa160, 0xc0000a4410, 0xb15380, 0xc0000807c0, 0xc00002f400, 0xc0000f4000, ...)
21:23:19Z device-mqtt[1778]:       /root/go/pkg/mod/github.com/edgexfoundry/device-sdk-go@v1.2.2/pkg/service/main.go:74 +0x7f1
21:23:19Z device-mqtt[1778]: github.com/edgexfoundry/device-sdk-go/pkg/startup.Bootstrap(0xa4022b, 0x11, 0xaf925c, 0x5, 0x9fa160, 0xc0000a4410)
21:23:19Z device-mqtt[1778]:       /root/go/pkg/mod/github.com/edgexfoundry/device-sdk-go@v1.2.2/pkg/startup/bootstrap.go:19 +0x112
21:23:19Z device-mqtt[1778]: main.main()
```

### PR DESCRIPTION
**Pull request by weichou1229**
Fix #160

Signed-off-by: weichou <weichou1229@gmail.com>

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://wiki.edgexfoundry.org/display/FA/Contributor%27s+Guide
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?
Service will panic when the config is unable to load.

Issue Number: #160 

## What is the new behavior?
Return error instead of the panic if required config not found and modify the config username and pwd to optional field.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

### CODE REVIEW

**Review by lenny-intel — DISMISSED** [review]
Perfect!

**Comment by cloudxxx8** [comment]
@weichou1229 please rebase

**Comment by weichou1229** [comment]
Rebased.

**Review by cloudxxx8 — APPROVED** [review]
LGTM

**Pull request merged**
