### PR TITLE
fix(build): update to go 1.16

### PR DESCRIPTION
**Pull request by tonyespy**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [NA] Tests for the changes have been added (for bug fixes / features)
- [NA] Docs have been added / updated (for bug fixes / features)

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/device-mqtt-go/blob/master/.github/CONTRIBUTING.md

## What is the current behavior?
This PR updates the service to use go 1.16 (including the snap build), and also fixes a snap build breakage caused by recent build changes.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## New Imports

- [ ] Yes
- [ x] No

### CODE REVIEW

**Review by lenny-intel — APPROVED** [review]
LGTM

**Comment by lenny-intel** [comment]
recheck

**Comment by lenny-intel** [comment]
@tonyespy,  Need to add `go mod tidy` in the snap just before the `make build`

**Comment by tonyespy** [comment]
> @tonyespy, Need to add `go mod tidy` in the snap just before the `make build`
> or @ernestojeda can the `tidy` be added to the Snap builds in the Ci pipeline?

Thanks! I just force pushed an update that does this, and am creating PRs and/or including it in other open PRs where required.

**Review by lenny-intel — APPROVED** [review]
LGTM

**Pull request merged**
